# Generated by Django 6.0.1 on 2026-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_online_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery (COD)'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
    ]
